FROM crystallang/crystal:1-alpine

WORKDIR /app

COPY . .

RUN shards install --without-development

RUN mkdir -p bin

RUN shards build --static --release --no-debug

FROM scratch

COPY --from=0 /app/bin/milka /milka

CMD ["/milka"]
